## Numpy

NumPy is a fundamental library for specific computing in Python. It provides support for ararys and matrices, along with a collection of mathematical functions to operate on these data structures. 

In [69]:
import numpy as np

#### Create 1D Array

In [70]:
## create a 1D array

arr1 = np.array([1,2,3,4,5])
print(arr1)
print(type(arr1))
print(arr1.shape)

[1 2 3 4 5]
<class 'numpy.ndarray'>
(5,)


### Reshape from 1D to 2D

In [49]:
## reshape 1D to 2D

arr2 = np.array([1,2,3,4,5])
arr2.reshape(1,5)              # means 1 row and 5 columns

array([[1, 2, 3, 4, 5]])

In [50]:
arr2 = np.array([[1,2,3,4,5]])
arr2.shape

(1, 5)

#### Create 2D Array

In [51]:
## 2D array

arr2 = np.array([[1,2,3,4,5], [5,4,3,2,1]])
print(arr2)
print(arr2.shape)

[[1 2 3 4 5]
 [5 4 3 2 1]]
(2, 5)


### Creating array by using in-built function

In [ ]:
# Creating array by using in-built function

np.arange(0,10,2)

array([0, 2, 4, 6, 8])

In [53]:
np.ones((3,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [54]:
# identity matrix

np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

### Attributes of Numpy array

In [55]:
## Attributes of Numpy array

arr = np.array([[1,2,3], [4,5,6]])

print("Array:\n", arr)
print("Shape:", arr.shape)
print("Number of dimensions:", arr.ndim)
print("Size (number of elements):", arr.size)
print("Data type:", arr.dtype)
print("Item size(in bytes):", arr.itemsize)

Array:
 [[1 2 3]
 [4 5 6]]
Shape: (2, 3)
Number of dimensions: 2
Size (number of elements): 6
Data type: int64
Item size(in bytes): 8


### Numpy Vectorized Operation

In [56]:
### Numpy Vectorized Operation
arr1 = np.array([1,2,3,4,5])
arr2 = np.array([10,20,30,40,50])

### Element wise addition
print("Addition:", arr1 + arr2)

### Element wise substraction
print("Substraction:", arr1 - arr2)

### Element wise multiplication
print("Multiplication:", arr1 * arr2)

### Element wise division
print("Division:", arr1 / arr2)


Addition: [11 22 33 44 55]
Substraction: [ -9 -18 -27 -36 -45]
Multiplication: [ 10  40  90 160 250]
Division: [0.1 0.1 0.1 0.1 0.1]


### Universal functions

In [ ]:
## Universal functions
arr = np.array([2,3,4,5,6])

## Square root
print("Square root:", np.sqrt(arr))

## Exponential
print("Exponential:", np.exp(arr))

## Sine
print("Sine:", np.sin(arr))

## Natural Log
print("Natural Log:", np.log(arr))

Square root: [1.41421356 1.73205081 2.         2.23606798 2.44948974]
Exponential: [  7.3890561   20.08553692  54.59815003 148.4131591  403.42879349]
Sine: [ 0.90929743  0.14112001 -0.7568025  -0.95892427 -0.2794155 ]
Natural Log: [0.69314718 1.09861229 1.38629436 1.60943791 1.79175947]


### Array Slicing and Indexing

In [58]:
## Array Slicing and Indexing

arr = np.array([[1,2,3,4], [5,6,7,8], [9,10,11,12]])
print("Array:  \n", arr)


Array:  
 [[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [59]:
print(arr[0])

[1 2 3 4]


In [60]:
print(arr[0][0])

1


In [61]:
print(arr[1:])

[[ 5  6  7  8]
 [ 9 10 11 12]]


In [62]:
print(arr[0:2, 2:])

[[3 4]
 [7 8]]


### Modify array elements

In [63]:
## Modify array elements
arr = np.array([[1,2,3,4], [5,6,7,8], [9,10,11,12]])
print("Array:  \n", arr)

arr[0][0]=100
print("Modified1: \n", arr)

arr[1:]=45
print("Modified2: \n", arr)

Array:  
 [[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
Modified1: 
 [[100   2   3   4]
 [  5   6   7   8]
 [  9  10  11  12]]
Modified2: 
 [[100   2   3   4]
 [ 45  45  45  45]
 [ 45  45  45  45]]


### Statistical Concepts - Normalization

In [64]:
### Statistical Concepts - Normalization : to have a mean of 0 and standard deviation of 1

data = np.array([1,2,3,4,5])
print(data)

# Calculate the mean and standard deviation
mean = np.mean(data)
std_dev = np.std(data)

# Print the mean and standard deviation
print(mean)
print(std_dev)

# Normalize the data
normalized_data = (data - mean) / std_dev
print("Normalized data:", normalized_data)

[1 2 3 4 5]
3.0
1.4142135623730951
Normalized data: [-1.41421356 -0.70710678  0.          0.70710678  1.41421356]


In [65]:
data = np.array([1,2,3,4,5,6,7,8,9,10])

# mean
mean = np.mean(data)
print("Mean:", mean)

# median
median = np.median(data)
print("Median:", median)


# standard deviation
std_dev = np.std(data)
print("Standard Deviation:", std_dev)

# variance
variance = np.var(data)
print("Variance:", variance)

Mean: 5.5
Median: 5.5
Standard Deviation: 2.8722813232690143
Variance: 8.25


## Logical Operations

In [66]:
## Logical Operations

data = np.array([1,2,3,4,5,6,7,8,9])

data > 5
data[data > 5]
data[(data >= 5) & (data <=8)]

array([5, 6, 7, 8])